spring.application.name=ai_monitor1
spring.datasource.url=jdbc:mysql://localhost:3306/mentor_ai
spring.datasource.username=root
spring.datasource.password=madyhoc09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=mySuperSecureSecretKeyForJwtSigning12345
jwt.expiration=86400000
